#!/usr/bin/env bash

# Usage
if [ "$1" == "" ];
then
	echo "Usage: `basename $0` [deploy] [COMMENT]"
	echo "[COMMENT] is for commit hexo source code, need to connet by '-'"
	echo "ex: this-is-a-commit-msg"
	exit 0
fi

ACTION=$1
COMMENT=$2

if [ ${ACTION} == "deploy" ];
then
	# Hexo modify themes and deploy
	echo "deploy start:"
	hexo clean
	hexo generate
	hexo deploy
fi

# push hexo source
if [ ${ACTION} != "" ];
then
	if [ ${COMMENT} != "" ];
	then
		echo "push start:"
		git commit -am ${COMMENT}
		git push
	fi
fi

