#!/usr/bin/env bash

# Usage
if [ "$1" == "" ];
then
	echo "Usage: `basename $0` [deploy] [COMMENT]"
	echo "[COMMENT] is for commit hexo source code, need to connet by '-'"
	echo "ex: this-is-a-commit-msg"
	exit 0
fi

echo $2

if [ $1 == "deploy" ];
then
	# Hexo modify themes and deploy all (themes + post)
	echo "deploy start:"
	hexo clean
	hexo generate
	hexo deploy
fi

# push hexo source
if [ $1 != "" ];
then
	if [ "$2" != "" ];
	then
		echo "push start:"
		git add .
		git commit -m "$2"
		git push
	fi
fi

